{{- range $tmpindex, $platform := until ( int $.Values.platform.num )}} 
{{- $index := add $tmpindex 1 -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx{{ $index }}-conf
  namespace: {{ $.Release.Namespace }}
data:
  default.conf: "server {\n    listen       80;\n    server_name  localhost;\n    #charset koi8-r;\n    #access_log  logs/host.access.log  main;\n    location / {\n        root   /usr/local/nginx/html;\n        index  index.html index.htm;\n        try_files $uri $uri/ /index.html;\n    }\n    \n    location  ^~ /prod-api/ {\n    \tproxy_pass http://gateway{{ $index }}.{{ $.Release.Namespace }}.svc.cluster.local:8080/;\n    }\n\n\terror_page   500 502 503 504  /50x.html;\n    location = /50x.html {\n        root   html;\n    }\n}\n"

---
{{- end }}
